# These are supported funding model platforms

github: [livonix]
patreon: livonix
open_collective: livonix
ko_fi: livonix
tidelift:
community_bridge:
liberapay:
issuehunt:
lfx_crowdfunding:
polar:
buy_me_a_coffee: livonix
thanks_dev:
custom: 
  - https://github.com/sponsors/livonix
  - https://buymeacoffee.com/livonix
