/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // OpenSound Design System Colors
        "tertiary": "#ec63ff",
        "on-primary": "#39008c",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#370086",
        "surface-bright": "#2c2c2d",
        "on-background": "#ffffff",
        "on-primary-container": "#2b006e",
        "on-error-container": "#ffb2b9",
        "secondary": "#53ddfc",
        "primary-fixed": "#ae8dff",
        "on-surface-variant": "#adaaab",
        "on-tertiary-fixed-variant": "#660075",
        "surface-dim": "#0e0e0f",
        "error-container": "#a70138",
        "inverse-primary": "#6e3bd7",
        "on-secondary-fixed-variant": "#005969",
        "on-tertiary-container": "#19001e",
        "surface-container-highest": "#262627",
        "primary-fixed-dim": "#a27cff",
        "tertiary-fixed": "#f487ff",
        "tertiary-container": "#de4bf4",
        "on-secondary-fixed": "#003a45",
        "on-surface": "#ffffff",
        "surface-container": "#1a191b",
        "primary-dim": "#8455ef",
        "primary": "#ba9eff",
        "inverse-surface": "#fcf8f9",
        "inverse-on-surface": "#565556",
        "secondary-container": "#00687a",
        "background": "#0e0e0f",
        "outline": "#767576",
        "secondary-fixed-dim": "#48d4f3",
        "on-tertiary-fixed": "#300038",
        "surface-variant": "#262627",
        "outline-variant": "#484849",
        "on-tertiary": "#3d0047",
        "tertiary-fixed-dim": "#ef6eff",
        "error-dim": "#d73357",
        "surface-container-lowest": "#000000",
        "tertiary-dim": "#ec63ff",
        "on-error": "#490013",
        "on-secondary": "#004b58",
        "error": "#ff6e84",
        "secondary-fixed": "#65e1ff",
        "surface-container-low": "#131314",
        "on-secondary-container": "#ecfaff",
        "primary-container": "#ae8dff",
        "surface": "#0e0e0f",
        "surface-container-high": "#201f21",
        "surface-tint": "#ba9eff",
        "secondary-dim": "#40ceed",
        
        // Legacy Spotify colors for compatibility
        'spotify-green': '#1DB954',
        'spotify-black': '#191414',
        'spotify-dark': '#121212',
        'spotify-gray': '#B3B3B3',
        'spotify-light-gray': '#E5E5E5',
        'spotify-highlight': '#282828',
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body": ["Manrope", "system-ui", "sans-serif"],
        "label": ["Manrope", "system-ui", "sans-serif"],
        'sans': ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "0.25rem", 
        "lg": "0.5rem", 
        "xl": "0.75rem", 
        "full": "9999px"
      },
      animation: {
        'spin-slow': 'spin 3s linear infinite',
        'pulse-slow': 'pulse 3s ease-in-out infinite',
        'fade-in': 'fadeIn 0.3s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      backdropBlur: {
        xs: '2px',
      },
    },
  },
  plugins: [],
}
